#######################################################
# https://app.vagrantup.com/jhcook/boxes/macos-sierra
#######################################################


# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "jhcook/macos-sierra"
  config.vm.hostname = "macos-sierra"
  # set auto_update to false, if you do NOT want to check the correct additions version when booting this machine
  config.vbguest.auto_update = false
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  config.vm.network "private_network", ip: "192.168.33.11"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.synced_folder "htdocs", "/var/www/html"
  #config.vm.provision "shell", path: "config.sh"
  #
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    
    # Customize the amount of memory on the VM:
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    
    # Set the number of virtual CPUs for the virtual machine
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    
    # Give the VM access to the host's CD/DVD drive, by attaching the medium to the virtual IDE controller
    #vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port 0", "--device 0", "--type", "dvddrive"]

    # Customize motherboard chipset
    # vb.customize ["modifyvm", :id, "--chipset", "ich9"]

    # Customize NAT DNS
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # Set resolution on macOS
    #Values: 0 = 640x480, 1 = 800x600, 2 = 1024x768, 3 = 1280x1024, 4 = 1440x900, 5 = 1920x1200
    vb.customize ["setextradata", :id, "VBoxInternal2/EfiGopMode", "5"]
    vb.customize ["setextradata", :id, "CustomVideoMode1", "1920x1080x32"]
    vb.customize ["setextradata", :id, "GUI/CustomVideoMode1", "1920x1080x32"]
  end
  #
  #
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
    ansible.verbose = true
    ansible.sudo = true
  end
end